image: gitpod/workspace-docker

tasks:
  - init: |
      curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      k3d cluster create mycluster --wait
      kubectl create namespace argocd
      kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - command: sleep infinity
